### PR TITLE
fix: Omitting consumer version selectors should fall back to tags

### LINKED ISSUE #1157: Cannot run provider verification tests when using @PactBroker(tags = ...) (since 4.1.5)
No pacts are found. 

Introduced by one of these PRs:

https://github.com/DiUS/pact-jvm/pull/1147
https://github.com/DiUS/pact-jvm/pull/1143

@pendsley

### PR DESCRIPTION
**Pull request by pendsley**
Fixes #1157 

Tested locally with:
No tags, No consumer version selectors
Only tags, no version selectors
No tags, Only version selectors
Tags and version selectors (Should prefer version selectors)

### CODE REVIEW

File: provider/junit/src/test/groovy/au/com/dius/pact/provider/junit/loader/PactBrokerLoaderSpec.groovy [hunk 1]
```diff
@@ -653,16 +720,13 @@ class PactBrokerLoaderSpec extends Specification {
       loader.pactReader = mockReader
       loader
     }
-    def selectors = [
-      new ConsumerVersionSelector('latest', true)
```
Comment (pendsley) [inline provider/junit/src/test/groovy/au/com/dius/pact/provider/junit/loader/PactBrokerLoaderSpec.groovy:657]: In hind sight, this should've been a red flag
